WITH w AS (
  SELECT
    PROVIDER_BUSINESS_GROUP_NBR,
    PAYMENT_METHOD_CD,
    SERVICE_CD,
    SERVICE_TYPE_CD,
    PLACE_OF_SERVICE_CD,
    RATE,
    MAX(RATE) OVER (
      PARTITION BY PROVIDER_BUSINESS_GROUP_NBR, PAYMENT_METHOD_CD, SERVICE_CD, SERVICE_TYPE_CD, PLACE_OF_SERVICE_CD
    ) AS max_rate
  FROM CET_RATES
  WHERE CONTRACT_TYPE = 'N'
)
SELECT
  PROVIDER_BUSINESS_GROUP_NBR,
  PAYMENT_METHOD_CD,
  SERVICE_CD,
  SERVICE_TYPE_CD,
  PLACE_OF_SERVICE_CD,
  max_rate,
  COUNT(*) AS rows_at_max_rate
FROM w
WHERE RATE = max_rate
GROUP BY
  PROVIDER_BUSINESS_GROUP_NBR, PAYMENT_METHOD_CD, SERVICE_CD, SERVICE_TYPE_CD, PLACE_OF_SERVICE_CD, max_rate
HAVING COUNT(*) > 1
ORDER BY rows_at_max_rate DESC;
