WITH ranked AS (
  SELECT
    PROVIDER_BUSINESS_GROUP_NBR,
    PROVIDER_BUSINESS_GROUP_SCORE_NBR,
    PRODUCT_CD,
    RATING_SYSTEM_CD,
    EPDB_GEOGRAPHIC_AREA_CD,
    ROW_NUMBER() OVER (
      PARTITION BY PROVIDER_IDENTIFICATION_NBR, NETWORK_ID, SERVICE_LOCATION_NBR
      ORDER BY PROVIDER_BUSINESS_GROUP_SCORE_NBR DESC
    ) AS rn
  FROM prv_ps_ce_dev.hcb_dev.CET_PROVIDERS
  WHERE PROVIDER_IDENTIFICATION_NBR = 4861169
    AND NETWORK_ID = '2020P'
    AND SERVICE_LOCATION_NBR = 5783780
)
SELECT
  PROVIDER_BUSINESS_GROUP_NBR,
  PROVIDER_BUSINESS_GROUP_SCORE_NBR,
  PRODUCT_CD,
  RATING_SYSTEM_CD,
  EPDB_GEOGRAPHIC_AREA_CD
FROM ranked
WHERE rn = 1;
