select PROVIDER_BUSINESS_GROUP_NBR, SERVICE_GROUPING_PRIORITY_NBR, SERVICE_GROUP_CHANGED_IND, ph.PAYMENT_METHOD_CD, ph.SCORE, RATE
from CET_RATES r
join PAYMENT_METHOD_HIERARCHY ph
  on ph.PAYMENT_METHOD_CD = r.PAYMENT_METHOD_CD
where PROVIDER_BUSINESS_GROUP_NBR = 164568027
  and PRODUCT_CD = 'MEPO'
  and SERVICE_CD = '19101'
  and SERVICE_TYPE_CD = 'CPT4'
  and PLACE_OF_SERVICE_CD = '22';

select PROVIDER_BUSINESS_GROUP_NBR, SERVICE_GROUPING_PRIORITY_NBR, SERVICE_GROUP_CHANGED_IND, ph.PAYMENT_METHOD_CD, ph.SCORE, RATE
from CET_RATES r
join PAYMENT_METHOD_HIERARCHY ph
  on ph.PAYMENT_METHOD_CD = r.PAYMENT_METHOD_CD
where PROVIDER_BUSINESS_GROUP_NBR = 454681176
  and PRODUCT_CD = 'MHMO'
  and SERVICE_CD = '72130'
  and SERVICE_TYPE_CD = 'CPT4'
  and PLACE_OF_SERVICE_CD = '22';

select PROVIDER_BUSINESS_GROUP_NBR, SERVICE_GROUPING_PRIORITY_NBR, SERVICE_GROUP_CHANGED_IND, ph.PAYMENT_METHOD_CD, ph.SCORE, RATE
from CET_RATES r
join PAYMENT_METHOD_HIERARCHY ph
  on ph.PAYMENT_METHOD_CD = r.PAYMENT_METHOD_CD
where PROVIDER_BUSINESS_GROUP_NBR = 219986066
  and PRODUCT_CD = 'MHMO'
  and SERVICE_CD = '93597'
  and SERVICE_TYPE_CD = 'CPT4'
  and PLACE_OF_SERVICE_CD = '22';

select PROVIDER_BUSINESS_GROUP_NBR, SERVICE_GROUPING_PRIORITY_NBR, SERVICE_GROUP_CHANGED_IND, ph.PAYMENT_METHOD_CD, ph.SCORE, RATE
from CET_RATES r
join PAYMENT_METHOD_HIERARCHY ph
  on ph.PAYMENT_METHOD_CD = r.PAYMENT_METHOD_CD
where PROVIDER_BUSINESS_GROUP_NBR = 259876981
  and PRODUCT_CD = 'MHMO'
  and SERVICE_CD = 'C8913'
  and SERVICE_TYPE_CD = 'HCPC'
  and PLACE_OF_SERVICE_CD = '22';

select PROVIDER_BUSINESS_GROUP_NBR, SERVICE_GROUPING_PRIORITY_NBR, SERVICE_GROUP_CHANGED_IND, ph.PAYMENT_METHOD_CD, ph.SCORE, RATE
from CET_RATES r
join PAYMENT_METHOD_HIERARCHY ph
  on ph.PAYMENT_METHOD_CD = r.PAYMENT_METHOD_CD
where PROVIDER_BUSINESS_GROUP_NBR = 210907876
  and PRODUCT_CD = 'MHMO'
  and SERVICE_CD = '71555'
  and SERVICE_TYPE_CD = 'CPT4'
  and PLACE_OF_SERVICE_CD = '22';

select PROVIDER_BUSINESS_GROUP_NBR, SERVICE_GROUPING_PRIORITY_NBR, SERVICE_GROUP_CHANGED_IND, ph.PAYMENT_METHOD_CD, ph.SCORE, RATE
from CET_RATES r
join PAYMENT_METHOD_HIERARCHY ph
  on ph.PAYMENT_METHOD_CD = r.PAYMENT_METHOD_CD
where PROVIDER_BUSINESS_GROUP_NBR = 694252090
  and PRODUCT_CD = 'MHMO'
  and SERVICE_CD = '74261'
  and SERVICE_TYPE_CD = 'CPT4'
  and PLACE_OF_SERVICE_CD = '22';

select PROVIDER_BUSINESS_GROUP_NBR, SERVICE_GROUPING_PRIORITY_NBR, SERVICE_GROUP_CHANGED_IND, ph.PAYMENT_METHOD_CD, ph.SCORE, RATE
from CET_RATES r
join PAYMENT_METHOD_HIERARCHY ph
  on ph.PAYMENT_METHOD_CD = r.PAYMENT_METHOD_CD
where PROVIDER_BUSINESS_GROUP_NBR = 726266271
  and PRODUCT_CD = 'MHMO'
  and SERVICE_CD = '77067'
  and SERVICE_TYPE_CD = 'CPT4'
  and PLACE_OF_SERVICE_CD = '22';

select PROVIDER_BUSINESS_GROUP_NBR, SERVICE_GROUPING_PRIORITY_NBR, SERVICE_GROUP_CHANGED_IND, ph.PAYMENT_METHOD_CD, ph.SCORE, RATE
from CET_RATES r
join PAYMENT_METHOD_HIERARCHY ph
  on ph.PAYMENT_METHOD_CD = r.PAYMENT_METHOD_CD
where PROVIDER_BUSINESS_GROUP_NBR = 254959616
  and PRODUCT_CD = 'MPPO'
  and SERVICE_CD = '73725'
  and SERVICE_TYPE_CD = 'CPT4'
  and PLACE_OF_SERVICE_CD = '22';

select PROVIDER_BUSINESS_GROUP_NBR, SERVICE_GROUPING_PRIORITY_NBR, SERVICE_GROUP_CHANGED_IND, ph.PAYMENT_METHOD_CD, ph.SCORE, RATE
from CET_RATES r
join PAYMENT_METHOD_HIERARCHY ph
  on ph.PAYMENT_METHOD_CD = r.PAYMENT_METHOD_CD
where PROVIDER_BUSINESS_GROUP_NBR = 174652377
  and PRODUCT_CD = 'MPPO'
  and SERVICE_CD = '71275'
  and SERVICE_TYPE_CD = 'CPT4'
  and PLACE_OF_SERVICE_CD = '22';

select PROVIDER_BUSINESS_GROUP_NBR, SERVICE_GROUPING_PRIORITY_NBR, SERVICE_GROUP_CHANGED_IND, ph.PAYMENT_METHOD_CD, ph.SCORE, RATE
from CET_RATES r
join PAYMENT_METHOD_HIERARCHY ph
  on ph.PAYMENT_METHOD_CD = r.PAYMENT_METHOD_CD
where PROVIDER_BUSINESS_GROUP_NBR = 164568027
  and PRODUCT_CD = 'MPPO'
  and SERVICE_CD = '38589'
  and SERVICE_TYPE_CD = 'CPT4'
  and PLACE_OF_SERVICE_CD = '22';

select PROVIDER_BUSINESS_GROUP_NBR, SERVICE_GROUPING_PRIORITY_NBR, SERVICE_GROUP_CHANGED_IND, ph.PAYMENT_METHOD_CD, ph.SCORE, RATE
from CET_RATES r
join PAYMENT_METHOD_HIERARCHY ph
  on ph.PAYMENT_METHOD_CD = r.PAYMENT_METHOD_CD
where PROVIDER_BUSINESS_GROUP_NBR = 489704468
  and PRODUCT_CD = 'MPPO'
  and SERVICE_CD = '26485'
  and SERVICE_TYPE_CD = 'CPT4'
  and PLACE_OF_SERVICE_CD = '24';

select PROVIDER_BUSINESS_GROUP_NBR, SERVICE_GROUPING_PRIORITY_NBR, SERVICE_GROUP_CHANGED_IND, ph.PAYMENT_METHOD_CD, ph.SCORE, RATE
from CET_RATES r
join PAYMENT_METHOD_HIERARCHY ph
  on ph.PAYMENT_METHOD_CD = r.PAYMENT_METHOD_CD
where PROVIDER_BUSINESS_GROUP_NBR = 630549560
  and PRODUCT_CD = 'MPPO'
  and SERVICE_CD = '54000'
  and SERVICE_TYPE_CD = 'CPT4'
  and PLACE_OF_SERVICE_CD = '11';

select PROVIDER_BUSINESS_GROUP_NBR, SERVICE_GROUPING_PRIORITY_NBR, SERVICE_GROUP_CHANGED_IND, ph.PAYMENT_METHOD_CD, ph.SCORE, RATE
from CET_RATES r
join PAYMENT_METHOD_HIERARCHY ph
  on ph.PAYMENT_METHOD_CD = r.PAYMENT_METHOD_CD
where PROVIDER_BUSINESS_GROUP_NBR = 51346551
  and PRODUCT_CD = 'MPPO'
  and SERVICE_CD = '74713'
  and SERVICE_TYPE_CD = 'CPT4'
  and PLACE_OF_SERVICE_CD = '22';

select PROVIDER_BUSINESS_GROUP_NBR, SERVICE_GROUPING_PRIORITY_NBR, SERVICE_GROUP_CHANGED_IND, ph.PAYMENT_METHOD_CD, ph.SCORE, RATE
from CET_RATES r
join PAYMENT_METHOD_HIERARCHY ph
  on ph.PAYMENT_METHOD_CD = r.PAYMENT_METHOD_CD
where PROVIDER_BUSINESS_GROUP_NBR = 394877805
  and PRODUCT_CD = 'MPPO'
  and SERVICE_CD = 'C7528'
  and SERVICE_TYPE_CD = 'HCPC'
  and PLACE_OF_SERVICE_CD = '24';
